{{ if .Values.__CONFIG__.__NAME__.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "__GLOBAL__.__NAME__PVCName" . }}
  labels:
{{ include "__GLOBAL__.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.__CONFIG__.__NAME__.accessModes }}
  resources:
    requests:
      storage: {{ .Values.__CONFIG__.__NAME__.size }}

{{ end }}
