# Default values for firefly-iii.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jc5x/firefly-iii
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  default:
    create: true
    name: ''

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  traefik: true
  annotations: {}
  hosts:
  - host: firefly-iii.local
    paths:
    - /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
persistance:
  export:
    name: ''
    create: true
    size: 10Gi
    accessModes:
    - ReadWriteMany
  upload:
    name: ''
    create: true
    size: 10Gi
    accessModes:
    - ReadWriteMany

db:
  username: root
  password: nothing123
  name: firefly
  host:
  nameOverride: db

app:
  #Run the following command in a Linux/MacOS terminal: `echo base64:$(dd if=/dev/urandom bs=32 count=1 status=none | base64)`
  key: ENTER APP KEY. SEE COMMENT TO ON HOW TO GENERTATE
  #local / production
  env: production
